var dictionary = 
{
    "free" : { "head": {}, "def": [{ "text": "free", "pos": "adjective", "tr": [{ "text": "бесплатный", "pos": "прилагательное", "syn": [{ "text": "безвозмездный" }], "mean": [{ "text": "gratuitous" }], "ex": [{ "text": "free wifi", "tr": [{ "text": "бесплатный Wi" }] }, { "text": "free gift", "tr": [{ "text": "безвозмездный дар" }] }] }, { "text": "свободный", "pos": "прилагательное", "syn": [{ "text": "вольный" }, { "text": "несвободный" }, { "text": "беспрепятственный" }], "mean": [{ "text": "available" }, { "text": "loose" }, { "text": "unimpeded" }], "ex": [{ "text": "free metabelian group", "tr": [{ "text": "свободная метабелева группа" }] }, { "text": "free Mason", "tr": [{ "text": "вольный каменщик" }] }, { "text": "free country", "tr": [{ "text": "несвободная страна" }] }, { "text": "free access", "tr": [{ "text": "беспрепятственный доступ" }] }] }] }, { "text": "free", "pos": "verb", "tr": [{ "text": "скачать", "pos": "глагол", "ex": [{ "text": "free download", "tr": [{ "text": "скачать бесплатно" }] }] }, { "text": "освободить", "pos": "глагол", "syn": [{ "text": "высвободить" }], "mean": [{ "text": "liberate" }, { "text": "unleash" }], "ex": [{ "text": "free hostages", "tr": [{ "text": "освободить заложников" }] }] }] }], "link": [{ "name": "lingvo", "href": "http://slovari.yandex.ru/free/en-ru/" }] },
    "javascript": { "head": {}, "def": [{ "text": "JavaScript", "pos": "noun", "tr": [{ "text": "яваскрипт", "pos": "существительное" }, { "text": "сценарий JavaScript", "pos": "существительное" } ] } ], "link": [{ "name": "lingvo", "href": "http://slovari.yandex.ru/javascript/en-ru/" } ] },
    "blablabla" : {"head":{},"def":[]},
    "camels": {"head":{},"def":[]},
    "camel": {"head":{},"def":[{"text":"camel","pos":"noun","tr":[{"text":"верблюд","pos":"существительное","ex":[{"text":"Bactrian camel","tr":[{"text":"двугорбый верблюд"}]}]},{"text":"верблюдица","pos":"существительное","mean":[{"text":"she-camel"}]},{"text":"верблюдоводство","pos":"существительное","mean":[{"text":"camel breeding"}]},{"text":"верблюжонок","pos":"существительное"}]},{"text":"camel","pos":"adjective","tr":[{"text":"верблюжий","pos":"прилагательное","ex":[{"text":"camel racing","tr":[{"text":"верблюжьи бега"}]}]}]}],"link":[{"name":"lingvo-mobile","href":"http://m.slovari.yandex.ru/translate.xml?text=camel&lang=en-ru"}]},
    "revisions": {"head":{},"def":[{"text":"revisions","pos":"noun","tr":[{"text":"переделки","pos":"существительное"}]}]},
    "revision": {"head":{},"def":[{"text":"revision","pos":"noun","tr":[{"text":"пересмотр","pos":"существительное","syn":[{"text":"доработка"}],"mean":[{"text":"reconsideration"},{"text":"rework"}],"ex":[{"text":"TIR revision process","tr":[{"text":"процесс пересмотра МДП"}]},{"text":"final revision","tr":[{"text":"окончательная доработка"}]}]},{"text":"редакция","pos":"существительное","syn":[{"text":"версия"}],"mean":[{"text":"editorial"},{"text":"version"}],"ex":[{"text":"new revision","tr":[{"text":"новая редакция"}]},{"text":"BIOS revision","tr":[{"text":"версия BIOS"}]}]},{"text":"ревизия","pos":"существительное","mean":[{"text":"audit"}],"ex":[{"text":"revision date","tr":[{"text":"дата ревизии"}]}]},{"text":"изменение","pos":"существительное","mean":[{"text":"change"}],"ex":[{"text":"minor revisions","tr":[{"text":"незначительные изменения"}]}]},{"text":"пересмотренный вариант","pos":"существительное","mean":[{"text":"revised version"}]}]},{"text":"revision","pos":"adjective","tr":[{"text":"ревизионный","pos":"прилагательное","mean":[{"text":"audit"}],"ex":[{"text":"revision commission","tr":[{"text":"ревизионная комиссия"}]}]}]},{"text":"revision","pos":"verb","tr":[{"text":"пересмотреть","pos":"глагол","mean":[{"text":"revise"}],"ex":[{"text":"draft revision","tr":[{"text":"проект пересмотренного варианта"}]}]}]}],"link":[{"name":"lingvo-mobile","href":"http://m.slovari.yandex.ru/translate.xml?text=revision&lang=en-ru"}]}
}

